### PR TITLE
Log to file

### PR DESCRIPTION
**Pull request by Humoud**
The logger was configured to log only to the console. I added minor configs to allow it to log to file `catcher.log`.

### CODE REVIEW

**Comment by Akkowicz** [comment]
You can run it as a systemd service, logs will be stored in system journal.

Example configuration (CAP_NET_BIND_SERVICE) to bind to 80 port directly. Only use on a throwaway vm.

cat /etc/systemd/system/log4shell-honey.service 
```
[Unit]
Description=Legit Service
After=network.target

[Service]
User=honey
WorkingDirectory=/opt/honey
Type=simple
ExecStart=/usr/bin/python3 honey.py 80
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
DevicePolicy=closed
ProtectHome=true
ProtectSystem=full
SystemCallArchitectures=native
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

**Comment by Humoud** [comment]
Thanks for the quick Linux lesson @Akkowicz 😄 👍

**Comment by trpyn** [comment]
Thanks for the PR, I've merged it :)

**Comment by Humoud** [comment]
@entropyQueen Np, thanks for sharing and maintaining this project!

**Pull request merged**
